services:
  postgres:
    image: postgres:13
    container_name: wikipedia-scrapper_postgres
    environment:
      POSTGRES_DB: scrapper
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./pg_data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -d scrapper -U user
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    command: bash -c "alembic upgrade head && python main.py"
    restart: always
    container_name: app-container
    env_file: ./app/.env
    volumes:
      - type: bind
        source: ./logs
        target: /app/logs
    depends_on:
      postgres:
        condition: service_healthy